"""AG-UI Protocol: Agent-Gateway UI Communication Protocol.

This module defines the Pydantic schemas for AG-UI protocol messages,
matching the frontend TypeScript protocol definition.
"""

from app.agui.schemas import (
    AgentErrorMessage,
    AgentNotificationMessage,
    AgentNotificationPayload,
    AgentProgressMessage,
    AgentRequestMessage,
    AgentResultMessage,
    AgentStatusMessage,
    AgentToUIMessage,
    AgentToUIMessageType,
    AGUIEnvelope,
    AGUIEvent,
    AGUIEventType,
    AGUIProtocolVersion,
    JSONPatchOperation,
    StateSnapshotMessage,
    StateSnapshotPayload,
    StateSyncRequestMessage,
    StateSyncRequestPayload,
    StateUpdateMessage,
    StateUpdatePayload,
    UICancelMessage,
    UICommandMessage,
    UIContext,
    UIContextMessage,
    UIResponseMessage,
    UIToAgentMessage,
    UIToAgentMessageType,
    compute_checksum,
)

__all__ = [
    "AGUIEnvelope",
    "AGUIProtocolVersion",
    "AgentToUIMessage",
    "AgentToUIMessageType",
    "AgentStatusMessage",
    "AgentProgressMessage",
    "AgentResultMessage",
    "AgentErrorMessage",
    "AgentRequestMessage",
    "AgentNotificationMessage",
    "AgentNotificationPayload",
    "UIToAgentMessage",
    "UIToAgentMessageType",
    "UICommandMessage",
    "UIResponseMessage",
    "UICancelMessage",
    "UIContextMessage",
    "UIContext",
    "AGUIEvent",
    "AGUIEventType",
    # State sync protocol
    "JSONPatchOperation",
    "StateUpdateMessage",
    "StateUpdatePayload",
    "StateSyncRequestMessage",
    "StateSyncRequestPayload",
    "StateSnapshotMessage",
    "StateSnapshotPayload",
    "compute_checksum",
]
